version = 1

test_patterns = [
  "packages/javascript/packages/autogrammer/src/**/*.ts",
  "packages/javascript/packages/autogrammer/src/**/*.ts",
]

exclude_patterns = [
  "packages/javascript/packages/autogrammer/src/**/*.test.ts", 
  "packages/javascript/packages/autogrammer/test/**/*.ts", 
  "packages/javascript/packages/autogrammer/src/**/*.test.ts", 
  "packages/javascript/packages/autogrammer/test/**/*.ts", 
  # "examples/**", 
  # "scripts/**", 
  # "test/**", 
  "dev/**",
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "browser",
    "nodejs",
    "vitest"
  ]
  dialect = "typescript"
