name: "Cut Release for contort (Python)"

on:
  push:
    tags:
      - "py/contort-v*"

jobs:
  tagged-release:
    name: "Cut Release for contort (Python)"
    uses: ./.github/workflows/shared/python/release.yaml

    with:
      package: "./packages/contort/python"
      files: |
        packages/contort/python/dist/contort-*.tar.gz
        packages/contort/python/dist/contort-*.whl
