name: 'Tests // JS / json2gbnf'
on:
  pull_request:
    paths:
      - 'packages/javascript/packages/json2gbnf/**'
      - '.github/workflows/tests-js-json2gbnf.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: "Lint"
    uses: ./.github/workflows/shared/javascript/lint.yaml
    with:
      package: "./packages/javascript/packages/json2gbnf"

  unit-test:
    name: "Unit Test"
    uses: ./.github/workflows/shared/javascript/unit-test.yaml
    with:
      package: "./packages/javascript/packages/json2gbnf"

  build:
    name: "Build"
    uses: ./.github/workflows/shared/javascript/build.yaml
    with:
      package: "./packages/javascript/packages/json2gbnf"
