name: "Cut Release for contort (Javascript)"

on:
  push:
    tags:
      - "js/contort-v*"

jobs:
  release:
    name: "Cut Release for contort (Javascript)"
    uses: ./.github/workflows/shared/javascript/release.yaml

    with:
      package: "./packages/contort/javascript"
      files: |
        packages/contort/javascript/contort-*.tgz
