on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: ${{ inputs.package }}/dev-deps/python3.11/build.txt
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: pip install -U pip setuptools wheel 
        working-directory: ${{ inputs.package }}

      - name: Install build dependencies
        run: pip install -r dev-deps/python3.11/build.txt
        working-directory: ${{ inputs.package }}

      - name: Install dependencies
        run: pip install .
        working-directory: ${{ inputs.package }}

      - run: make build_package 
        working-directory: ${{ inputs.package }}
