on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string
      files:
        required: true
        description: "Newline-delimited list of path globs for asset files to upload"
      fail_on_unmatched_files: 
        required: false
        default: true
        type: boolean;
      generate_release_notes: 
        required: false
        default: true
        type: boolean;

jobs:
  release:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.11'
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: python -m pip install -U pip setuptools build
        working-directory: ${{ inputs.package }}

      - run: make build_package 
        working-directory: ${{ inputs.package }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: ${{ inputs.fail_on_unmatched_files }} 
          generate_release_notes: ${{ inputs.generate_release_notes }}
          files: ${{ inputs.files }}
