name: 'Tests // JS / Autogrammer'
on:
  pull_request:
    paths:
      - 'packages/autogrammer/javascript/**'
      - '.github/workflows/js-autogrammer-test.yaml'
      - '.github/workflows/js-shared-unit-test.yaml'
      - '.github/workflows/js-shared-integration-test.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: "Autogrammer / Lint"
    uses: ./.github/workflows/js-shared-lint.yaml
    with:
      package: ./packages/autogrammer/javascript

  unit-test:
    name: "Autogrammer / Unit Test"
    uses: ./.github/workflows/js-shared-unit-test.yaml
    with:
      package: ./packages/autogrammer/javascript

  build:
    name: "Autogrammer / Build"
    uses: ./.github/workflows/js-shared-build.yaml
    with:
      package: ./packages/autogrammer/javascript
