name: Publish Autogrammer (Javascript) to NPM

on:
  push:
    tags:
      - "js/autogrammer-v*"

jobs:
  publish:
    uses: ./.github/workflows/shared/javascript/publish.yaml
    with:
      package: "./packages/autogrammer/javascript"
