name: Version Contortionist (Javascript)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/contort/**/*.ts'
      - 'packages/contort/README.md'
      - 'packages/contort/**/*.gbnf'
      - '!packages/contort/**/*.test.ts'
      # - '!packages/contort/package.json'

jobs:
  version:
    uses: ./.github/workflows/js-shared-version.yaml
    with:
      package: "./packages/contort/javascript"
      tag_prefix: "js/contort-v"
    secrets: inherit
