name: Publish contort (Javascript) to NPM

on:
  push:
    tags:
      - "js/contort-v*"

jobs:
  publish:
    uses: ./.github/workflows/js-shared-publish.yaml
    with:
      package: "./packages/contort"
    secrets: inherit
