name: "Cut Release for contort (Javascript)"

on:
  workflow_dispatch:
  push:
    tags:
      - "js/contort-v*"

jobs:
  release:
    name: "Cut Release for contort (Javascript)"
    uses: ./.github/workflows/js-shared-release.yaml

    with:
      package: "./packages/contort"
      files: |
        packages/contort/contort-*.tgz
