name: Publish gbnf (Javascript) to NPM

on:
  push:
    tags:
      - "js/gbnf-v*"

jobs:
  publish:
    uses: ./.github/workflows/js-shared-publish.yaml
    with:
      package: "./packages/gbnf/javascript"
