name: Publish SQL2GBNF (Javascript) to NPM

on:
  push:
    tags:
      - "js/sql2gbnf-v*"

jobs:
  publish:
    uses: ./.github/workflows/js-shared-publish.yaml
    secrets: inherit
    with:
      package: "./packages/sql2gbnf/javascript"
