on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

      site_id:
        required: true
        description: "Netlify site ID"
        type: string

env:
  FORCE_COLOR: "1"

jobs:
  docs:
    name: 'Docs'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install 

      - name: Build docsanova
        working-directory: 'packages/docsanova'
        run: pnpm build

      - name: Install bin/docsanova
        run: pnpm install 

      - name: 'Build Docs'
        working-directory: ${{ inputs.package }}
        run: 'pnpm build'


      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: './build'
          production-branch: main
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          # enable-pull-request-comment: false
          # enable-commit-comment: true
          # overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ inputs.site_id }}
        timeout-minutes: 1

