name: 'Tests // JS / sql2gbnf'
on:
  pull_request:
    paths:
      - 'packages/sql2gbnf/javascript/**'
      - '.github/workflows/js-sql2gbnf-test.yaml'
      - '.github/workflows/js-shared-unit-test.yaml'
      - '.github/workflows/js-shared-integration-test.yaml'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'pnpm-workspace.yaml'
      - 'tsconfig.json'

env:
  FORCE_COLOR: "1"

jobs:
  lint:
    name: "Javascript / SQL2GBNF / Lint"
    uses: ./.github/workflows/js-shared-lint.yaml
    with:
      package: "./packages/sql2gbnf/javascript"

  unit-test:
    name: "Javascript / sql2gbnf / Unit Test"
    uses: ./.github/workflows/js-shared-unit-test.yaml
    with:
      package: "./packages/sql2gbnf/javascript"

  integration-test:
    name: "Javascript / sql2gbnf / Integration Test"
    uses: ./.github/workflows/js-shared-integration-test.yaml
    with:
      package: "./packages/sql2gbnf/javascript"

  build:
    name: "Javascript / SQL2GBNF / Build"
    uses: ./.github/workflows/js-shared-build.yaml
    with:
      package: "./packages/sql2gbnf/javascript"


  coverage-test:
    name: "Javascript / sql2gbnf / Coverage Test"

    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v4
        with:
          lfs: 'true'

      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        working-directory: "./packages/sql2gbnf/javascript"
        run: pnpm install

      - name: 'Coverage Test'
        working-directory: "./packages/sql2gbnf/javascript"
        run: 'NODE_OPTIONS=--trace-deprecation pnpm test:coverage -- --no-write'
