name: Publish Autogrammer (Python) to PyPI

on:
  push:
    tags:
      - "py/autogrammer-v*"

jobs:
  publish:
    uses: ./.github/workflows/py-shared-publish.yaml
    with:
      package: "./packages/autogrammer/python"

permissions:
  id-token: write
  contents: read
