on:
  workflow_call:
    inputs:
      package:
        required: true
        description: "Path to package"
        type: string

jobs:
  publish:
    runs-on: "ubuntu-latest"


    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608
      - uses: actions/setup-python@61a6322f88396a6271a6ee3565807d608ecaddd1
        with:
          python-version: '3.11'
      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - run: python -m pip install -U pip setuptools build
        working-directory: ${{ inputs.package }}

      - run: make build_package 
        working-directory: ${{ inputs.package }}

      - name: Publish
        uses: pypa/gh-action-pypi-publish@b7f401de30cb6434a1e19f805ff006643653240e
        with:
          verbose: true
          working-directory: ${{ inputs.package }}/dist
